name: flutter_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  favorite_button: ^0.0.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0+2
  flutter_rating_bar: 4.0.0

  #smooth_star_rating: 1.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_switch: ^0.3.2
  animated_toggle_switch: ^0.5.2
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_home.png"
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/lisa.png
    - assets/images/ic_us.png
    - assets/images/fruit_market.png
    - assets/images/mix_fruit_png_11.png
    - assets/images/page1_1.png
    - assets/images/page2_2.png
    - assets/images/page3_3.png
    - assets/images/fruit_home.png
    - assets/images/google_icon.png
    - assets/images/icon_facebook.png
    -  assets/images/ic_delete.png
    - assets/images/ic_loading.png
    - assets/images/ic_sentcode.png
    - assets/images/ic_alarm.png
    - assets/images/ic_dautay.jpg
    - assets/images/ic_giaca.png
    - assets/images/ic_GPS.png
    - assets/images/ic_home.png
    - assets/images/ic_remove.png
    - assets/images/ic_favorite.png
    - assets/images/ic_user.png
    - assets/images/ic_shopping.png
    - assets/images/ic_edit.png
    - assets/images/ic_my_oder.png
    - assets/images/ic_giaca1.png
    - assets/images/ic_favorite2.png
    - assets/images/ic_setting.png
    - assets/images/ic_mycart.png
    - assets/images/ic_rateus.png
    - assets/images/ic_share.png
    - assets/images/ic_logout.png
    - assets/images/ic_help.png
    - assets/images/ic_alarmsetting.png
    - assets/images/ic_profile.png
    - assets/images/ic_language.png
    - assets/images/ic_changaAddress.png
    - assets/images/ic_secure.png
    - assets/images/ic_delete1.png
    - assets/images/ic_delete2.png
    - assets/images/ic_market.png
    - assets/images/ic_gps1.png
    - assets/images/ic_card.png
    - assets/images/ic_matercard.png
    - assets/images/ic_master2.png
    - assets/images/ic_visa.png
    - assets/images/ic_phonepay.png
    - assets/images/ic_paypal.png
    - assets/images/ic_ggpay.png
    - assets/images/ic_line.png
    - assets/images/ic_atmcard.png
    - assets/images/ic_notfavorite.png
    - assets/images/ic_favorites1.png
    - assets/fruit/CAM1.jpg
    - assets/fruit/gihangtraicay.jpg
    - assets/fruit/giotraicay.jpg
    - assets/fruit/goiquatraicay.jpg
    - assets/fruit/goiquatraicay1.jpg
    - assets/fruit/goiquatraicay2.jpg
    - assets/fruit/hatde.jpg
    - assets/fruit/hatde1.jpg
    - assets/fruit/hạt cười.jpg
    - assets/fruit/liaorange.jpg
    - assets/fruit/manyfruit.jpg
    - assets/fruit/melon-bingo.jpg
    - assets/fruit/melon-duahau.jpg
    - assets/fruit/melonduavang.jpg
    - assets/fruit/nho.jpg
    - assets/fruit/nhoden.jpg
    - assets/fruit/nhothom.jpg
    - assets/fruit/orange.jpg
    - assets/fruit/orange1.jpg
    - assets/fruit/papertraicaygiay.jpg
    - assets/fruit/orange2.jpg
    - assets/fruit/quadao-peaches.jpg
    - assets/fruit/quaman.jpg
    - assets/fruit/stone2.jpg
    - assets/fruit/Stonefruit1.jpg
    - assets/fruit/xoai.jpg
    - assets/fruit/nhan.jpg
    - assets/fruit/mit.jpeg
    - assets/fruit/chuoi.jpg
    - assets/fruit/vai.jpg
    - assets/images/fvd/aanpaper.jpg
    - assets/images/fvd/caibap.jpg
    - assets/images/fvd/caibong.jpg
    - assets/images/fvd/caithao.jpg
    - assets/images/fvd/carot.jpg
    - assets/images/fvd/carottim.jpg
    - assets/images/fvd/cherry.jpg
    - assets/images/fvd/cucaitrang.jpg
    - assets/images/fvd/cudau.jpg
    - assets/images/fvd/daokho.jpg
    - assets/images/fvd/dautam.webp
    - assets/images/fvd/dolac.jpg
    - assets/images/fvd/dotuong.webp
    - assets/images/fvd/doxanh.jpg
    - assets/images/fvd/dua.jpg
    - assets/images/fvd/goiraucu.jpeg
    - assets/images/fvd/gung.jpg
    - assets/images/fvd/hanhnhan.jpg
    - assets/images/fvd/hanhtay.jpg
    - assets/images/fvd/hanhtim.jpg
    - assets/images/fvd/hatde1.jpg
    - assets/images/fvd/hatdieu.jpg
    - assets/images/fvd/hatocho.jpg
    - assets/images/fvd/hatcuoi.jpg
    - assets/images/fvd/khoai kang.webp
    - assets/images/fvd/latiato.jpg
    - assets/images/fvd/mango.jpg
    - assets/images/fvd/mankho.jpg
    - assets/images/fvd/mantau.jpg
    - assets/images/fvd/mamxoi.jpg
    - assets/images/fvd/mamxoiden.jpg
    - assets/images/fvd/melon-duahau.jpg
    - assets/images/fvd/melonduavang.jpg
    - assets/images/fvd/mixeddry.webp
    - assets/images/fvd/mixeddry1.webp
    - assets/images/fvd/mixedry.jpg
    - assets/images/fvd/nghe.jpg
    - assets/images/fvd/nghexanh.jpg
    - assets/images/fvd/nhieuhat.jpg
    - assets/images/fvd/nhokho.jpg
    - assets/images/fvd/oliu.webp
    - assets/images/fvd/quamanz.jpg
    - assets/images/fvd/raucu.jpg
    - assets/images/fvd/raucu2.jpg
    - assets/images/fvd/raucu3.jpg
    - assets/images/fvd/rauma.jpg
    - assets/images/fvd/raumui.jpg
    - assets/images/fvd/raungot.webp
    - assets/images/fvd/rauriep.jpg
    - assets/images/fvd/stone2.jpg
    - assets/images/fvd/sungtay.jpg
    - assets/images/fvd/taotau.jpg
    - assets/images/fvd/toi.jpg
    - assets/images/fvd/toiden.jpg
    - assets/images/fvd/vai.jpg
    - assets/images/fvd/xoai.jpg
    - assets/images/fvd/xoaido.jpg
    - assets/images/fvd/doden.jpg
    - assets/images/fvd/nhieuqua.jpg
    - assets/images/fvd/nhieuqua1.jpg
    - assets/images/fvd/nhieuqua2.jpg
    - assets/images/fvd/nhieuqua3.jpg
    - assets/images/fvd/nhieuqua4.jpg
    - assets/images/fvd/quadao.jpg
    - assets/images/fvd/mo.jpg
    - assets/images/fvd/duale.jpg
    - assets/images/fvd/duavang.jpg
    - assets/images/fvd/duaech.jpg
    - assets/images/fvd/bingo.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:



  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

        - asset: assets/fonts/Poppins-Black.ttf

        - asset: assets/fonts/Poppins-BlackItalic.ttf
    - family: Icon_home
      fonts:
          - asset: assets/icons/ic_home.ttf
    - family: User_icon
      fonts:
        - asset: assets/icons/User_icon.ttf
    - family: Shopping_icon
      fonts:
        - asset: assets/icons/Shopping_icon.ttf
    - family: Iconfavorite
      fonts:
        - asset: assets/icons/ic_favorive.ttf
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
